name: Test, lint, and deploy

on:
  workflow_call:
    inputs:
      skip_tests:
        description: "Skip pipeline tests"
        type: string
        required: false
        default: 'false'
      folder:
        description: "Working folder"
        type: string
        required: false
        default: '.'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.folder }}
  cancel-in-progress: true

jobs:
  actions:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Prepare working folder'
        if: "inputs.folder != '.'"
        run: cp -r ${{ inputs.folder }}/. .

      - name: 'Set node version'
        id: set-node-version
        run: |
          node_version=$(jq '.engines.node' package.json)
          echo "node_version=${node_version:1:-1}" >> $GITHUB_OUTPUT

      - name: 'Setup node'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.set-node-version.outputs.node_version }}

      - name: 'Cache node modules'
        id: cache
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: 'Install'
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm set @moogur:registry=https://npm.pkg.github.com/
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"
          npm ci

      - name: 'Lint'
        run: npm run lint

      - name: 'Build'
        run: npm run build

      - name: 'Test'
        if: "inputs.skip_tests != 'true'"
        run: npm run test:coverage
