name: Deploy for docker container

on:
  workflow_call:
    inputs:
      github_user:
        description: "The Github user who started workflow"
        type: string
        required: false
        default: $GITHUB_ACTOR

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker-job:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Global env"
        id: global_env
        run: |
          echo "IMAGE_NAME=${{ github.event.repository.name }}" >> $GITHUB_OUTPUT
          echo "DOCKERHUB_IMAGE_NAME=docker.pkg.github.com/${{ inputs.github_user }}/${{ github.event.repository.name }}/${{ github.event.repository.name }}" >> $GITHUB_OUTPUT

      - name: "Determining the version"
        id: version
        run: |
          if [[ ${{ github.event_name }} == 'push' ]]; then
            raw_tag=`echo $(git describe --tags --abbrev=0)`
            echo "VERSION=${raw_tag}" >> $GITHUB_OUTPUT
          else
            version=$(date +"%d.%m.%Y-auto")
            echo "VERSION=${version}" >> $GITHUB_OUTPUT
          fi

      - name: "Build and tag image"
        run: |
          docker build -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:latest" -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}" .

      - name: "docker login"
        run: docker login docker.pkg.github.com -u ${{ inputs.github_user }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: "Publish image"
        run: |
          docker push "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}"
          docker push "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:latest"
