name: Deploy for backend

on:
  workflow_call:
    inputs:
      github_user:
        description: "The Github user who started workflow"
        type: string
        required: false
        default: $GITHUB_ACTOR

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker-job:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Set node version'
        id: set-node-version
        run: |
          node_version=$(jq '.engines.node' package.json)
          echo "node_version=${node_version:1:-1}" >> $GITHUB_OUTPUT

      - name: 'Global env'
        id: global_env
        run: |
          echo "IMAGE_NAME=${{ github.event.repository.name }}" >> $GITHUB_OUTPUT
          echo "DOCKERHUB_IMAGE_NAME=docker.pkg.github.com/${{ inputs.github_user }}/${{ github.event.repository.name }}/${{ github.event.repository.name }}" >> $GITHUB_OUTPUT

      - name: 'Version'
        id: version
        run: |
          raw_tag=`echo $(git describe --tags --abbrev=0)`
          echo "VERSION=${raw_tag#v}" >> $GITHUB_OUTPUT

      - name: 'Build and tag image'
        run: |
          docker build --build-arg ARG_NODE_VERSION="${{ steps.set-node-version.outputs.node_version }}" --build-arg ARG_APP_VERSION="${{ steps.version.outputs.VERSION }}" -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:latest" -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}" .

      - name: 'docker login'
        run: docker login docker.pkg.github.com -u ${{ inputs.github_user }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: 'Publish image'
        run: |
          docker push "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}"
          docker push "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:latest"
