name: Deploy for build application

on:
  workflow_call:
    inputs:
      file_path:
        description: "The path to the execution file"
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-application-job:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Determining the version"
        id: version
        run: |
          raw_tag=`echo $(git describe --tags --abbrev=0)`
          echo "VERSION=${raw_tag}" >> $GITHUB_OUTPUT

      - name: Build project
        run: |
          . ${{ inputs.file_path }}
          ls -la .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          release_name: Release ${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: application.zip
          asset_name: application.zip
          asset_content_type: application/zip
