name: Build and Deploy

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Set node version'
        id: set-node-version
        run: |
          node_version=$(jq '.engines.node' package.json)
          echo "node_version=${node_version:1:-1}" >> $GITHUB_OUTPUT

      - name: 'Setup node'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.set-node-version.outputs.node_version }}

      - name: 'Cache node modules'
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: 'Install'
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: 'Build'
        run: npm run build

      - name: Minio Deploy
        uses: moogur/minio-deploy-action@master
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: ${{ secrets.MINIO_BUCKET }}
          source_dir: 'dist'
          target_dir: '/'
