name: Deploy for backend

on:
  workflow_call:
    inputs:
      workdir:
        description: "Working directory (below repository root)"
        type: string
        required: false
        default: "."

permissions:
  contents: write
  # packages: write
  # issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker-job:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Set go version'
        id: set-go-version
        run: |
          go_version=$(cat go.mod | grep "go[[:space:]]" | sed 's/.*[[:space:]]//')
          echo "go_version=$go_version" >> $GITHUB_OUTPUT

      - name: 'Setup go'
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.set-go-version.outputs.go_version }}

      - name: 'Run GoReleaser'
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
          workdir: ${{ inputs.workdir }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
