name: Kanboard for single branch

on:
  workflow_call:
    inputs:
      kanboard_columns:
        description: "List of column ids, in order, from left to right, separated by commas"
        type: string
        required: true

jobs:
  kanboard:
    runs-on: ubuntu-latest
    if: "github.event_name == 'push'"

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Set variables'
        id: variables
        run: |
          wget -O ./request.sh https://raw.githubusercontent.com/moogur/all-workflows/master/scripts/kanboard_request.sh
          chmod +x ./request.sh

          auth_data=${{ secrets.KANBOARD_USER }}:${{ secrets.KANBOARD_TOKEN }}

          sed -i "s|url=|url=${{ secrets.KANBOARD_HOST }}|" ./request.sh
          sed -i "s|auth_data=|auth_data=$auth_data|" ./request.sh

      - name: "Transferring the task to the in progress status"
        run: |
          . ./request.sh
          IFS=',' read -r -a all_columns <<< "${{ inputs.kanboard_columns }}"
          task_id=`echo $(git log -1 --pretty=%B) | tr "-" " " | tr "]" " " | awk '{print $2 }'`
          task_info=`echo $(request getTask {\"task_id\":$task_id})`
          column_id=`echo $(jq '.result.column_id' <<< "$task_info")`

          if [[ -z $column_id ]]; then
            result=$task_info
          elif [[ "${all_columns[3]}" != $column_id ]] && [[ "${all_columns[*]}" =~ $column_id ]]; then
            project_id=`echo $(jq '.result.project_id' <<< "$task_info")`
            swimlane_id=`echo $(jq '.result.swimlane_id' <<< "$task_info")`
            result=`echo $(request moveTaskPosition {\"project_id\":$project_id,\"task_id\":$task_id,\"column_id\":${all_columns[3]},\"position\":1,\"swimlane_id\":$swimlane_id})`
          fi

          echo "$result"
