name: Pull request annotation (test)

on:
  workflow_call:
    inputs:
      skip_tests:
        description: "Skip pipeline tests"
        type: string
        required: false
        default: 'false'
      folder:
        description: "Working folder"
        type: string
        required: false
        default: '.'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.folder }}
  cancel-in-progress: true

jobs:
  scanner:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Prepare working folder'
        if: "inputs.folder != '.'"
        run: cp -r ${{ inputs.folder }}/. .

      - name: 'Set go version'
        id: set-go-version
        run: |
          go_version=$(cat go.mod | grep "go[[:space:]]" | sed 's/.*[[:space:]]//')
          echo "go_version=$go_version" >> $GITHUB_OUTPUT

      - name: 'Setup go'
        if: "inputs.skip_tests != 'true'"
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.set-go-version.outputs.go_version }}

      - name: Run golint
        if: "inputs.skip_tests != 'true'"
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run ./... --out-format=checkstyle > report.xml
